# Use Node.js as base image
FROM node:20-alpine

# Set work directory
WORKDIR /app/client

# Get npm dependencies
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy in the rest of the app before building
COPY . .

# Use alpine's non-root user
# RUN chown -R node:node /app/client
# USER node

# Build static files for production
RUN npm run build