/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as WatershedWebcloudRunIdRouteImport } from './routes/watershed.$webcloudRunId'
import { Route as AboutScenariosRouteImport } from './routes/about/scenarios'
import { Route as AboutAboutWeppCloudRouteImport } from './routes/about/about-wepp-cloud'
import { Route as AboutAboutWeppRouteImport } from './routes/about/about-wepp'
import { Route as AboutAboutWatarRouteImport } from './routes/about/about-watar'
import { Route as AboutAboutSbsRouteImport } from './routes/about/about-sbs'
import { Route as AboutAboutRhessysRouteImport } from './routes/about/about-rhessys'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const WatershedWebcloudRunIdRoute = WatershedWebcloudRunIdRouteImport.update({
  id: '/watershed/$webcloudRunId',
  path: '/watershed/$webcloudRunId',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutScenariosRoute = AboutScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAboutWeppCloudRoute = AboutAboutWeppCloudRouteImport.update({
  id: '/about-wepp-cloud',
  path: '/about-wepp-cloud',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAboutWeppRoute = AboutAboutWeppRouteImport.update({
  id: '/about-wepp',
  path: '/about-wepp',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAboutWatarRoute = AboutAboutWatarRouteImport.update({
  id: '/about-watar',
  path: '/about-watar',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAboutSbsRoute = AboutAboutSbsRouteImport.update({
  id: '/about-sbs',
  path: '/about-sbs',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAboutRhessysRoute = AboutAboutRhessysRouteImport.update({
  id: '/about-rhessys',
  path: '/about-rhessys',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/about/about-rhessys': typeof AboutAboutRhessysRoute
  '/about/about-sbs': typeof AboutAboutSbsRoute
  '/about/about-watar': typeof AboutAboutWatarRoute
  '/about/about-wepp': typeof AboutAboutWeppRoute
  '/about/about-wepp-cloud': typeof AboutAboutWeppCloudRoute
  '/about/scenarios': typeof AboutScenariosRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/about/about-rhessys': typeof AboutAboutRhessysRoute
  '/about/about-sbs': typeof AboutAboutSbsRoute
  '/about/about-watar': typeof AboutAboutWatarRoute
  '/about/about-wepp': typeof AboutAboutWeppRoute
  '/about/about-wepp-cloud': typeof AboutAboutWeppCloudRoute
  '/about/scenarios': typeof AboutScenariosRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
  '/about': typeof AboutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRoute
  '/about/about-rhessys': typeof AboutAboutRhessysRoute
  '/about/about-sbs': typeof AboutAboutSbsRoute
  '/about/about-watar': typeof AboutAboutWatarRoute
  '/about/about-wepp': typeof AboutAboutWeppRoute
  '/about/about-wepp-cloud': typeof AboutAboutWeppCloudRoute
  '/about/scenarios': typeof AboutScenariosRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
  '/about/': typeof AboutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/team'
    | '/about/about-rhessys'
    | '/about/about-sbs'
    | '/about/about-watar'
    | '/about/about-wepp'
    | '/about/about-wepp-cloud'
    | '/about/scenarios'
    | '/watershed/$webcloudRunId'
    | '/about/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/team'
    | '/about/about-rhessys'
    | '/about/about-sbs'
    | '/about/about-watar'
    | '/about/about-wepp'
    | '/about/about-wepp-cloud'
    | '/about/scenarios'
    | '/watershed/$webcloudRunId'
    | '/about'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/team'
    | '/about/about-rhessys'
    | '/about/about-sbs'
    | '/about/about-watar'
    | '/about/about-wepp'
    | '/about/about-wepp-cloud'
    | '/about/scenarios'
    | '/watershed/$webcloudRunId'
    | '/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TeamRoute: typeof TeamRoute
  WatershedWebcloudRunIdRoute: typeof WatershedWebcloudRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/watershed/$webcloudRunId': {
      id: '/watershed/$webcloudRunId'
      path: '/watershed/$webcloudRunId'
      fullPath: '/watershed/$webcloudRunId'
      preLoaderRoute: typeof WatershedWebcloudRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/scenarios': {
      id: '/about/scenarios'
      path: '/scenarios'
      fullPath: '/about/scenarios'
      preLoaderRoute: typeof AboutScenariosRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/about-wepp-cloud': {
      id: '/about/about-wepp-cloud'
      path: '/about-wepp-cloud'
      fullPath: '/about/about-wepp-cloud'
      preLoaderRoute: typeof AboutAboutWeppCloudRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/about-wepp': {
      id: '/about/about-wepp'
      path: '/about-wepp'
      fullPath: '/about/about-wepp'
      preLoaderRoute: typeof AboutAboutWeppRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/about-watar': {
      id: '/about/about-watar'
      path: '/about-watar'
      fullPath: '/about/about-watar'
      preLoaderRoute: typeof AboutAboutWatarRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/about-sbs': {
      id: '/about/about-sbs'
      path: '/about-sbs'
      fullPath: '/about/about-sbs'
      preLoaderRoute: typeof AboutAboutSbsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/about-rhessys': {
      id: '/about/about-rhessys'
      path: '/about-rhessys'
      fullPath: '/about/about-rhessys'
      preLoaderRoute: typeof AboutAboutRhessysRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutAboutRhessysRoute: typeof AboutAboutRhessysRoute
  AboutAboutSbsRoute: typeof AboutAboutSbsRoute
  AboutAboutWatarRoute: typeof AboutAboutWatarRoute
  AboutAboutWeppRoute: typeof AboutAboutWeppRoute
  AboutAboutWeppCloudRoute: typeof AboutAboutWeppCloudRoute
  AboutScenariosRoute: typeof AboutScenariosRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAboutRhessysRoute: AboutAboutRhessysRoute,
  AboutAboutSbsRoute: AboutAboutSbsRoute,
  AboutAboutWatarRoute: AboutAboutWatarRoute,
  AboutAboutWeppRoute: AboutAboutWeppRoute,
  AboutAboutWeppCloudRoute: AboutAboutWeppCloudRoute,
  AboutScenariosRoute: AboutScenariosRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TeamRoute: TeamRoute,
  WatershedWebcloudRunIdRoute: WatershedWebcloudRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
