/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutWeppCloudRouteImport } from './routes/about-wepp-cloud'
import { Route as AboutWeppRouteImport } from './routes/about-wepp'
import { Route as AboutWatarRouteImport } from './routes/about-watar'
import { Route as AboutSbsRouteImport } from './routes/about-sbs'
import { Route as AboutRhessysRouteImport } from './routes/about-rhessys'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatershedWebcloudRunIdRouteImport } from './routes/watershed.$webcloudRunId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutWeppCloudRoute = AboutWeppCloudRouteImport.update({
  id: '/about-wepp-cloud',
  path: '/about-wepp-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutWeppRoute = AboutWeppRouteImport.update({
  id: '/about-wepp',
  path: '/about-wepp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutWatarRoute = AboutWatarRouteImport.update({
  id: '/about-watar',
  path: '/about-watar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSbsRoute = AboutSbsRouteImport.update({
  id: '/about-sbs',
  path: '/about-sbs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRhessysRoute = AboutRhessysRouteImport.update({
  id: '/about-rhessys',
  path: '/about-rhessys',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatershedWebcloudRunIdRoute = WatershedWebcloudRunIdRouteImport.update({
  id: '/watershed/$webcloudRunId',
  path: '/watershed/$webcloudRunId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-rhessys': typeof AboutRhessysRoute
  '/about-sbs': typeof AboutSbsRoute
  '/about-watar': typeof AboutWatarRoute
  '/about-wepp': typeof AboutWeppRoute
  '/about-wepp-cloud': typeof AboutWeppCloudRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/scenarios': typeof ScenariosRoute
  '/team': typeof TeamRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-rhessys': typeof AboutRhessysRoute
  '/about-sbs': typeof AboutSbsRoute
  '/about-watar': typeof AboutWatarRoute
  '/about-wepp': typeof AboutWeppRoute
  '/about-wepp-cloud': typeof AboutWeppCloudRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/scenarios': typeof ScenariosRoute
  '/team': typeof TeamRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-rhessys': typeof AboutRhessysRoute
  '/about-sbs': typeof AboutSbsRoute
  '/about-watar': typeof AboutWatarRoute
  '/about-wepp': typeof AboutWeppRoute
  '/about-wepp-cloud': typeof AboutWeppCloudRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/scenarios': typeof ScenariosRoute
  '/team': typeof TeamRoute
  '/watershed/$webcloudRunId': typeof WatershedWebcloudRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-rhessys'
    | '/about-sbs'
    | '/about-watar'
    | '/about-wepp'
    | '/about-wepp-cloud'
    | '/login'
    | '/register'
    | '/scenarios'
    | '/team'
    | '/watershed/$webcloudRunId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-rhessys'
    | '/about-sbs'
    | '/about-watar'
    | '/about-wepp'
    | '/about-wepp-cloud'
    | '/login'
    | '/register'
    | '/scenarios'
    | '/team'
    | '/watershed/$webcloudRunId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-rhessys'
    | '/about-sbs'
    | '/about-watar'
    | '/about-wepp'
    | '/about-wepp-cloud'
    | '/login'
    | '/register'
    | '/scenarios'
    | '/team'
    | '/watershed/$webcloudRunId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutRhessysRoute: typeof AboutRhessysRoute
  AboutSbsRoute: typeof AboutSbsRoute
  AboutWatarRoute: typeof AboutWatarRoute
  AboutWeppRoute: typeof AboutWeppRoute
  AboutWeppCloudRoute: typeof AboutWeppCloudRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ScenariosRoute: typeof ScenariosRoute
  TeamRoute: typeof TeamRoute
  WatershedWebcloudRunIdRoute: typeof WatershedWebcloudRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-wepp-cloud': {
      id: '/about-wepp-cloud'
      path: '/about-wepp-cloud'
      fullPath: '/about-wepp-cloud'
      preLoaderRoute: typeof AboutWeppCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-wepp': {
      id: '/about-wepp'
      path: '/about-wepp'
      fullPath: '/about-wepp'
      preLoaderRoute: typeof AboutWeppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-watar': {
      id: '/about-watar'
      path: '/about-watar'
      fullPath: '/about-watar'
      preLoaderRoute: typeof AboutWatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-sbs': {
      id: '/about-sbs'
      path: '/about-sbs'
      fullPath: '/about-sbs'
      preLoaderRoute: typeof AboutSbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-rhessys': {
      id: '/about-rhessys'
      path: '/about-rhessys'
      fullPath: '/about-rhessys'
      preLoaderRoute: typeof AboutRhessysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watershed/$webcloudRunId': {
      id: '/watershed/$webcloudRunId'
      path: '/watershed/$webcloudRunId'
      fullPath: '/watershed/$webcloudRunId'
      preLoaderRoute: typeof WatershedWebcloudRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutRhessysRoute: AboutRhessysRoute,
  AboutSbsRoute: AboutSbsRoute,
  AboutWatarRoute: AboutWatarRoute,
  AboutWeppRoute: AboutWeppRoute,
  AboutWeppCloudRoute: AboutWeppCloudRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ScenariosRoute: ScenariosRoute,
  TeamRoute: TeamRoute,
  WatershedWebcloudRunIdRoute: WatershedWebcloudRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
