from django.db import models
from django.contrib.gis.db import models

# This is an auto-generated Django model module created by ogrinspect.
# /app/server $ django-admin ogrinspect server/watershed/data/OR/OR_drinking_water_source_areas.shp WatershedBorder --srid=4326 --mapping --multi
class WatershedBorder(models.Model):
    objectid = models.BigIntegerField()
    perimeter = models.FloatField()
    area = models.FloatField()
    acres = models.FloatField()
    delinsqmi = models.FloatField()
    tinwsys_is = models.FloatField()
    pws_id = models.CharField(max_length=10)
    pws_name = models.CharField(max_length=254)
    pws_label = models.CharField(max_length=50)
    tinwsys_d_field = models.CharField(max_length=5)
    tinwsf_is = models.CharField(max_length=7)
    tinwsf_nam = models.CharField(max_length=254)
    tinwsf_wat = models.CharField(max_length=28, null=True)
    src_label = models.CharField(max_length=254, null=True)
    dws_id = models.CharField(max_length=6, null=True)
    oregon_dwp = models.FloatField()
    city = models.CharField(max_length=30, null=True)
    cnty_name = models.CharField(max_length=10)
    epa_method = models.CharField(max_length=254, null=True)
    or_method = models.CharField(max_length=254, null=True)
    comments = models.CharField(max_length=254, null=True)
    fips_cnty = models.BigIntegerField()
    or_cnty_nu = models.FloatField()
    tinwsys_st = models.CharField(max_length=2, null=True)
    utm_zone = models.FloatField()
    sdwis_link = models.CharField(max_length=75)
    upstrm_cd = models.BigIntegerField()
    upstrmpwss = models.CharField(max_length=5, null=True)
    dwnstrm_cd = models.BigIntegerField()
    assessment = models.CharField(max_length=254)
    subbasin = models.CharField(max_length=254)
    subbasin_n = models.CharField(max_length=254)
    huc12_nhd = models.CharField(max_length=254, null=True)
    huc12_wbd = models.CharField(max_length=254, null=True)
    wrd_basin = models.CharField(max_length=35, null=True)
    date_del = models.DateField(null=True)
    initials_d = models.CharField(max_length=5, null=True)
    date_dig = models.DateField(null=True)
    initials_1 = models.CharField(max_length=5, null=True)
    date_proc = models.DateField(null=True)
    initials_p = models.CharField(max_length=5, null=True)
    method = models.CharField(max_length=10, null=True)
    comment = models.CharField(max_length=50, null=True)
    huc4_edit = models.CharField(max_length=10, null=True)
    separate = models.CharField(max_length=20, null=True)
    sqmi = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
