# Generated by Django 5.1.4 on 2025-02-28 19:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatershedBorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_m2', models.FloatField()),
                ('pws_id', models.CharField(max_length=10)),
                ('pws_name', models.CharField(max_length=254)),
                ('watershed_name', models.CharField(max_length=254, null=True)),
                ('watershed_id', models.CharField(max_length=50, null=True, unique=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('county', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=2, null=True)),
                ('huc12_nhd', models.CharField(max_length=254, null=True)),
                ('huc12_wbd', models.CharField(max_length=254, null=True)),
                ('sq_miles', models.FloatField()),
                ('webcloud_run_id', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('simplified_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
