# Generated by Django 5.1.4 on 2025-11-04 21:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topazid', models.IntegerField()),
                ('weppid', models.IntegerField()),
                ('order', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Subcatchment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topazid', models.IntegerField()),
                ('weppid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pws_id', models.CharField(max_length=9)),
                ('srcname', models.CharField(max_length=255)),
                ('pws_name', models.CharField(max_length=255)),
                ('county_nam', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=6, null=True)),
                ('huc10_id', models.CharField(max_length=12)),
                ('huc10_name', models.CharField(max_length=128)),
                ('wws_code', models.CharField(max_length=32)),
                ('srctype', models.CharField(max_length=32)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('runid', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('simplified_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
