# Generated by Django 5.1.4 on 2025-10-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='topaz_id',
        ),
    ]
