# Generated by Django 5.1.4 on 2025-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcatchment',
            name='aspect',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='avke',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='bd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='cancov',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='cancov_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='centroid_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='centroid_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='centroid_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='centroid_py',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='clay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='disturbed_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='hillslope_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='inrcov',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='inrcov_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='landuse_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='landuse_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='landuse_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='landuse_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='landuse_map',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='landuse_pct_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='ll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='man_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='man_fn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='mukey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='rilcov',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='rilcov_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='sand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='simple_texture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='slope_scalar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soil_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soil_build_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soil_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soil_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soil_fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soil_pct_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soils_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
