# Generated by Django 5.1.4 on 2026-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0002_subcatchment_aspect_subcatchment_avke_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcatchment',
            name='ll',
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='rock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatchment',
            name='soil_depth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
