# Generated by Django 5.1.4 on 2026-03-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0003_remove_subcatchment_ll_subcatchment_rock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watershed',
            name='county_nam',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='huc10_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='huc10_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='pws_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='pws_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='srcname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='srctype',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='state',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='watershed',
            name='wws_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
