# Generated by Django 5.1.4 on 2026-03-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0004_nullable_watershed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='watershed',
            name='area_km2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
